name: 💭 Suggestion
description: Submit a code change proposal
title: "Suggestion: "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your suggestion!
        We appreciate your help and will to help us improve and will review it as soon as we can!
  - type: textarea
    id: suggestion
    attributes:
      label: What is your suggestion about?
      description: Tell us, what do you want to suggest or what are your ideas you wish to share with us.
      placeholder: I think X could be better if we made it Y because...
    validations:
      required: true
