name: "Checks"

on:
  push:
    paths: [ ".github/workflows/*.yml", "**.rpy" ]

jobs:
  submod-checks:
    name: "Run submod checks"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Check"
        uses: "friends-of-monika/submod-check-action@v2"